version: '3'

services:
  ds-lab:
    container_name: spark-lab
    image: jupyter/all-spark-notebook:lab-3.6.3
    ports:
      - 8888:8888
    volumes:
      - ./data:/home/jovyan/work/data
      - ./spark:/home/jovyan/work/spark
      - ./images:/home/jovyan/work/images
    networks:
      - data-science

networks:
  data-science:
